#!/bin/bash

# Example build file, since I always forget the commands
# export path to Python config, so ./configure can find it
export PYTHON_CONFIG=/home/patrick/.local/lib/python3.10/site-packages

cd /home/patrick/hlrs/rust_rewrite/rust-ayudame/Ayudame

# full with ompt
./configure --prefix=/home/patrick/hlrs/rust_rewrite/installs/Ayudame/full --enable-rust --disable-doc --disable-ompt
make clean
make install