#!/bin/bash

# export path to Python config, so ./configure can find it
export PYTHON_CONFIG=/home/patrick/.local/lib/python3.10/site-packages

cd /home/patrick/hlrs/rust_rewrite/rust-ayudame/Ayudame

# minimal no ompt
./configure --prefix=/home/patrick/hlrs/rust_rewrite/installs/Ayudame/minimal-no-ompt --enable-rust=minimal --disable-doc --disable-ompt
make clean
make install
