[package]
name = "ayudame_wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
input_handler = { path = "../io_utils", package = "io_utils" }
utils = { path = "../utils", package = "utils" }